// <auto-generated />
namespace ProyectoPrograAvanzada.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddActualizarModelos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddActualizarModelos));
        
        string IMigrationMetadata.Id
        {
            get { return "202511200550380_AddActualizarModelos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
